dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: rom-import-9
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: rom64
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: rom65
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
